### ISSUE TITLE
What is the recommended way of getting max versioning from a collection?

### ISSUE THREAD

**Issue by RobSmyth** [WalkerCodeRanger/semver#87]
**Is your feature request related to a problem? Please describe.**

With ICompare depreciated in release 3.0.0 it is not clear to me what is the recommended way of obtaining the max (most recent) version from a collection. In was using the linq method Max().

**Describe the solution you'd like**

How to added to documentation. Or if something so obvious, and I just missed it, advice.

**Describe alternatives you've considered**

Pre 3.0.0 code:

```
{
   var versions = new List<SemVersion>();
      :  // A relatively small list is constructed
   return versions.Max();
}
```

My work around:

```
{
   var versions = new List<SemVersion>();
      :  // A relatively small list is constructed
    return versions.OrderByDescending(x => x, new SemverSortOrderComparer()).FirstOrDefault();
}

internal sealed class SemverSortOrderComparer : IComparer<SemVersion>
{
    public int Compare(SemVersion x, SemVersion y)
    {
        return x.CompareSortOrderTo(y);
    }
}
```

It does not feel right. It feels like I'm recreating what was depreciated.

**Additional context**

My application is not execution time critical. The list is small. My solution does not feel right.

With users migrating I wonder if others will need to solve the same issue.

**Comment by WalkerCodeRanger** [comment]
The recommended way of doing this is with the overload of `Max` that takes an `IComparer<T>` (available in .NET 6+) and the comparer provided by the library (i.e. `SemVersion.SortOrderComparer` or `SemVersion.PrecedenceComparer`).

```csharp
{
    var versions = new List<SemVersion>();
    // A relatively small list is constructed
    return versions.Max(SemVersion.SortOrderComparer);
}
```
This design makes it explicit whether you are ordering by sort order or precedence. This was causing confusion before (#9, #15) because the semantic version spec describes only precedence order, not sort order.

Hopefully, that feels like a good and also more explicit way of doing it. 

---

If you are using a version older than .NET 6, you can use `.OrderByDescending(x => x, SemVersion.SortOrderComparer).FirstOrDefault()` similar to what you did, or create an extension method:

```csharp
public static class EnumerableExtensions
{
#if !NET6_0_OR_GREATER
    public static TSource? Max<TSource>(this IEnumerable<TSource> source, IComparer<TSource> comparer)
        => source.OrderByDescending(x => x, comparer).FirstOrDefault();
#endif
}
```

**Comment by RobSmyth** [comment]
Thank you. Nice complete answer. Yep, I'm working with .NET standard 2.0.
