### ISSUE TITLE
Order by semver does not work anymore

### ISSUE THREAD

**Issue by TheFireCookie** [WalkerCodeRanger/semver#88]
**Describe the bug**
Previously you could create an object with a semver property and order by on it and now it does not work anymore.

**Steps To Reproduce**
1. Create a DTO with a semver property
2. Create a list of that DTO with some different values in the semver property
3. Order by that property
4. 
![image](https://github.com/user-attachments/assets/8424eaf0-1f9c-43b9-a08c-78700667e450)
![image](https://github.com/user-attachments/assets/a617fa09-8aa9-44b5-90eb-6ee8d7750e58)

**Expected behavior**
Order work like in version 2.3.0

**Versions(please complete the following information):**
 - Package Version: 3.0.0
 - Framework Version: .NET 8

**Additional context**

**Comment by TheFireCookie** [comment]
I've done some digging already and I saw that you tagged as obsolete and them removed the IComparable interface. Why is that? I think sorting of versions can be a relatively general use-case and should probably stay in the lib, or maybe you have another idea to do that in mind?

**Comment by WalkerCodeRanger** [comment]
Because there are two different ways to order semantic versions, you need to explicitly specify which order you want to use (i.e. `SemVersion.SortOrderComparer` or `SemVersion.PrecedenceComparer`). This change has been in the works for a while now because the previous way it worked was confusing users (#9, #15) since the semantic version specification only describes precedence order but the comparison order used to be sort order.

So your code should be changed to:
```csharp
migrations.OrderBy(m => m.Version, SemVersion.SortOrderComparer).ToArray();
```

This design makes it explicit whether you are ordering by sort order or precedence.

**Comment by TheFireCookie** [comment]
Ok it's working perfectly! Thanks!
