### ISSUE TITLE
Cake fails to resolve dependency of Semver 3.0.0

### ISSUE THREAD

**Issue by rngcntr** [WalkerCodeRanger/semver#90]
**Describe the bug**
We are using Semver in our dotnet cake file to configure the build depending on the version of our project. Since updating to Semver 3.0.0, our builds fail with the following error:
```
Could not load /data/tools/Addins/Semver.3.0.0/lib/net5.0/Semver.dll (missing Microsoft.Extensions.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
Error: Could not load file or assembly 'Microsoft.Extensions.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

**Steps To Reproduce**
I built a minimal working/non-working exampe which consists of only two lines of `build.cake`:
```
#addin nuget:?package=semver&version=3.0.0
Semver.SemVersion.Parse("1.0.0", Semver.SemVersionStyles.Any);
```
Using the official SDK Docker image, the build fails.
See https://github.com/rngcntr/semver-demo for further instructions.

**Expected behavior**
The build should succeed using version 3.0.0, as it did before with version 2.3.0

**Versions(please complete the following information):**
 - Package Version: 3.0.0
 - Framework Version: NET8, NET9

**Comment by WalkerCodeRanger** [comment]
I believe this is because Cake doesn't load dependencies of add-ins by default. The [Addin directive > Dependencies](https://cakebuild.net/docs/writing-builds/preprocessor-directives/addin#dependencies) section of the docs says this and says that you can specify `loaddependencies=true` to cause it to load dependencies. So your `build.cake` file would be:

```
#addin nuget:?package=semver&version=3.0.0&loaddependencies=true
Semver.SemVersion.Parse("1.0.0", Semver.SemVersionStyles.Any);
```

I haven't tried this myself yet, but I assume it will work. Please let me know if that doesn't address the problem.

_Why did this change with SemVer 3.0:_ The dependency on `Microsoft.Extensions.Primitives` primitives was added in v3.0.0. In v2.x.x versions there was no dependencies on any other NuGet packages. The dependency was added to replace and extend code that was previously part of the package for `StringSegement`. Using `Microsoft.Extensions.Primitives` improved performance because it uses `Span[T]`.

**Comment by rngcntr** [comment]
Thanks for your investigation. I can confirm that this solves the issue!

**Comment by AraHaan** [comment]
> _Why did this change with SemVer 3.0:_ The dependency on `Microsoft.Extensions.Primitives` primitives was added in v3.0.0. In v2.x.x versions there was no dependencies on any other NuGet packages. The dependency was added to replace and extend code that was previously part of the package for `StringSegement`. Using `Microsoft.Extensions.Primitives` improved performance because it uses `Span[T]`.

In that case why not replace that with the ``System.Memory`` package to get ``Span<T>``?
